version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ENABLE_V2=true
    command:
      - etcd
      - --name=etcd
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --initial-cluster-token=patroni-cluster
      - --initial-cluster-state=new
      - --initial-cluster=etcd=http://etcd:2380
      - --listen-peer-urls=http://0.0.0.0:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd-data
    networks:
      default:
        aliases:
          - etcd

  patroni_primary:
    build: 
      context: .
      dockerfile: Dockerfile.patroni
    environment:
      - PATRONI_SCOPE=shadowdb
      - PATRONI_NAME=primary
      - PATRONI_ETCD_URL=http://etcd:2379
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=primary:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "8008:8008"
    volumes:
      - pg_primary:/var/lib/postgresql/data
    depends_on:
      - etcd
    networks:
      default:
        aliases:
          - primary

  patroni_replica1:
    build: 
      context: .
      dockerfile: Dockerfile.patroni
    environment:
      - PATRONI_SCOPE=shadowdb
      - PATRONI_NAME=replica1
      - PATRONI_ETCD_URL=http://etcd:2379
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=replica1:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
    ports:
      - "5433:5432"
      - "8009:8008"
    volumes:
      - pg_replica1:/var/lib/postgresql/data
    depends_on:
      - etcd
    networks:
      default:
        aliases:
          - replica1

  patroni_replica2:
    build: 
      context: .
      dockerfile: Dockerfile.patroni
    environment:
      - PATRONI_SCOPE=shadowdb
      - PATRONI_NAME=replica2
      - PATRONI_ETCD_URL=http://etcd:2379
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=replica2:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
    ports:
      - "5434:5432"
      - "8010:8008"
    volumes:
      - pg_replica2:/var/lib/postgresql/data
    depends_on:
      - etcd
    networks:
      default:
        aliases:
          - replica2
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      default:
        aliases:
          - redis


volumes:
  pg_primary:
  pg_replica1:
  pg_replica2:
  patroni_data:
  etcd_data:
  redis_data:

