services:
  etcd:
    image: bitnami/etcd:3.5.0
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ENABLE_V2=true
      - ETCD_NAME=etcd
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=patroni-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd-data
    networks:
      default:
        aliases:
          - etcd

  patroni_primary:
    image: local/patroni:latest
    environment:
      - PATRONI_SCOPE=shadowdb
      - PATRONI_NAME=primary
      - PATRONI_ETCD_URL=http://etcd:2379
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=primary:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_POSTGRESQL_PARAMETERS_wal_level=replica
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_POSTGRESQL_PARAMETERS_max_wal_senders=10
      - PATRONI_POSTGRESQL_PARAMETERS_max_replication_slots=10
      - PATRONI_POSTGRESQL_PARAMETERS_synchronous_commit=on
      - PATRONI_POSTGRESQL_PARAMETERS_synchronous_standby_names='*'
      - PATRONI_POSTGRESQL_PARAMETERS_synchronous_mode=true
      - PATRONI_POSTGRESQL_PARAMETERS_synchronous_mode_strict=true
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD={PATRONI_REPLICATION_PASSWORD}
      - PATRONI_SLOTS_primary_type=physical
      - PATRONI_SLOTS_replica1_type=physical
      - PATRONI_SLOTS_replica2_type=physical
    ports:
      - "5432:5432"
      - "8008:8008"
    volumes:
      - pg_primary:/var/lib/postgresql/data
    depends_on:
      - etcd
    networks:
      default:
        aliases:
          - primary

  patroni_replica1:
    image: local/patroni:latest
    environment:
      - PATRONI_SCOPE=shadowdb
      - PATRONI_NAME=replica1
      - PATRONI_ETCD_URL=http://etcd:2379
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=replica1:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_POSTGRESQL_PARAMETERS_hot_standby=on
      - PATRONI_POSTGRESQL_PARAMETERS_hot_standby_feedback=on
      - PATRONI_POSTGRESQL_PARAMETERS_wal_level=replica
      - PATRONI_POSTGRESQL_PARAMETERS_max_wal_senders=10
      - PATRONI_POSTGRESQL_PARAMETERS_max_replication_slots=10
      - PATRONI_POSTGRESQL_PARAMETERS_synchronous_commit=remote_write
      - PATRONI_POSTGRESQL_PARAMETERS_wal_receiver_timeout=60s
      - PATRONI_POSTGRESQL_PARAMETERS_wal_receiver_status_interval=1s
      - PATRONI_POSTGRESQL_PARAMETERS_max_standby_streaming_delay=30s
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD={PATRONI_REPLICATION_PASSWORD}
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_SLOTS_replica1_type=physical
    ports:
      - "5433:5432"
      - "8009:8008"
    volumes:
      - pg_replica1:/var/lib/postgresql/data
    depends_on:
      - etcd
    networks:
      default:
        aliases:
          - replica1

  patroni_replica2:
    image: local/patroni:latest
    environment:
      - PATRONI_SCOPE=shadowdb
      - PATRONI_NAME=replica2
      - PATRONI_ETCD_URL=http://etcd:2379
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=replica2:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_POSTGRESQL_PARAMETERS_hot_standby=on
      - PATRONI_POSTGRESQL_PARAMETERS_hot_standby_feedback=on
      - PATRONI_POSTGRESQL_PARAMETERS_wal_level=replica
      - PATRONI_POSTGRESQL_PARAMETERS_max_wal_senders=10
      - PATRONI_POSTGRESQL_PARAMETERS_max_replication_slots=10
      - PATRONI_POSTGRESQL_PARAMETERS_synchronous_commit=remote_write
      - PATRONI_POSTGRESQL_PARAMETERS_wal_receiver_timeout=60s
      - PATRONI_POSTGRESQL_PARAMETERS_wal_receiver_status_interval=1s
      - PATRONI_POSTGRESQL_PARAMETERS_max_standby_streaming_delay=30s
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_REPLICATION_PASSWORD={PATRONI_REPLICATION_PASSWORD}
      - PATRONI_SLOTS_replica2_type=physical
    ports:
      - "5434:5432"
      - "8010:8008"
    volumes:
      - pg_replica2:/var/lib/postgresql/data
    depends_on:
      - etcd
    networks:
      default:
        aliases:
          - replica2
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      default:
        aliases:
          - redis
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"   # Prometheus default UI port
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      default:
        aliases:
          - prometheus         

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  # default Grafana port
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      default:
        aliases:
          - grafana

volumes:
  pg_primary:
  pg_replica1:
  pg_replica2:
  etcd_data:
  redis_data:
  grafana_data:

