scope: shadowdb
namespace: /db/
name: ${PATRONI_NAME}

restapi:
  listen: 0.0.0.0:8008
  connect_address: ${PATRONI_POSTGRESQL_CONNECT_ADDRESS}

etcd:
  url: ${PATRONI_ETCD_URL}

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true           
    synchronous_mode_strict: true  
    master_start_timeout: 300
    postgresql:
      use_pg_rewind: true
      use_slots: true  
      parameters:
        wal_keep_size: 1GB
        wal_level: replica        
        max_wal_senders: 10
        max_replication_slots: 10
        synchronous_commit: on     
        synchronous_standby_names: '*' 
        hot_standby: on            
        hot_standby_feedback: on    
        wal_log_hints: on  
      pg_hba:
        - "local all all trust"     
        - "local all postgres trust"  
        - "host replication replicator 0.0.0.0/0 md5"   
        - "host all all 0.0.0.0/0 md5"

postgresql:
  listen: ${PATRONI_POSTGRESQL_LISTEN}
  connect_address: ${PATRONI_POSTGRESQL_CONNECT_ADDRESS}
  data_dir: ${PATRONI_POSTGRESQL_DATA_DIR}
  authentication:
    replication:
      username: ${PATRONI_REPLICATION_USERNAME}
      password: ${PATRONI_REPLICATION_PASSWORD}
    superuser:
      username: ${PATRONI_SUPERUSER_USERNAME}
      password: ${PATRONI_SUPERUSER_PASSWORD}