scope: shadowdb
namespace: /db/
name: ${PATRONI_NAME}

restapi:
  listen: 0.0.0.0:8008
  connect_address: ${PATRONI_POSTGRESQL_CONNECT_ADDRESS}

etcd:
  url: ${PATRONI_ETCD_URL}

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    postgresql:
      use_pg_rewind: true
      parameters:
        wal_level: replica
        max_wal_senders: 10
        max_replication_slots: 10
      pg_hba:
        - "host replication replicator 0.0.0.0/0 trust"
        - "host all all 0.0.0.0/0 md5"

postgresql:
  listen: ${PATRONI_POSTGRESQL_LISTEN}
  connect_address: ${PATRONI_POSTGRESQL_CONNECT_ADDRESS}
  data_dir: ${PATRONI_POSTGRESQL_DATA_DIR}
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: node.Js03#